#!/bin/sh
# description: Start or stop the fhem server
# Added by Alex Peuchert


cd /opt/fhem

case "$1" in
'start')

        if ! start-stop-daemon -q -u fhem -K -t -x perl  ; then
	        echo  "Starting fhem..."
        	start-stop-daemon -u fhem -S -q -x perl fhem.pl fhem.cfg
	else
                echo "fhem is running"
	fi
        RETVAL=$?
        ;;
'stop')
        echo -n "Stopping fhem"
	start-stop-daemon  -q -u fhem -K -x perl
        RETVAL=$?
	
	for i in `seq 1 60` ; do
	        if start-stop-daemon -q -u fhem -K -t -x perl  ; then
			echo -n "."
			sleep 1
		else
			break
		fi
	done
	if start-stop-daemon -q -u fhem -K -t -x perl  ; then
		echo -n "  do kill -9,"
		start-stop-daemon  -q -u fhem -K -x perl -s 9
	fi
	if start-stop-daemon -q -u fhem -K -t -x perl  ; then
		echo " Error: FHEM still running!"
	else
		echo " stopped"
	fi
	RETVAL=0
        ;;
'status')
        if start-stop-daemon -q -u fhem -K -t -x perl  ; then
                echo "fhem is running"
        else
                echo "fhem is not running"
        fi
        ;;
*)
        echo "Usage: $0 { start | stop | status }"
        RETVAL=1
        ;;
esac
exit $RETVAL
