#!/bin/sh

#/bin/sed  -i -e s,^root:[^:]*:,root::, /etc/shadow
#sleep 3600

ROOT_MTDCHAR=/dev/mtd7
USER_MTDCHAR=/dev/mtd6
KERNEL_MTDCHAR=/dev/mtd5

echo "Erasing Kernel Flash ..."
flash_erase -q $KERNEL_MTDCHAR 0 0                      

ubidetach -p $USER_MTDCHAR
ubidetach -p $ROOT_MTDCHAR

echo "Erasing User Flash ..."
ubiformat -q $USER_MTDCHAR 
ubiattach -p $USER_MTDCHAR 
ubimkvol /dev/ubi0 -N user -m
ubidetach -p $USER_MTDCHAR

echo "Erasing Root Flash ..."
ubiformat -q $ROOT_MTDCHAR >/dev/null


echo secondary >/sys/module/plat_eq3ccu2/parameters/boot

echo
echo
echo Factory reset successful, please upload the stock firmware after reboot.
echo
echo

