#!/bin/sh
#
# set System Start Led Signal
#

SERIAL=$(cat /sys/module/plat_eq3ccu2/parameters/board_serial)

start() {
	printf "load CCU2 modules: "
	
	modprobe spidev
        modprobe ic200_spi
        modprobe spi_eq3_gpio
        modprobe spi_bitbang
        modprobe fsl_usb2_udc.ko
	
	# Tunneling
        modprobe tun
       
	# USB
        modprobe ehci-hcd
	modprobe sd_mod
	modprobe usb-storage
	modprobe vfat
	
	# MMC
	modprobe mxs-mmc
	modprobe mmc_block


	# HM/HmIP Dual Protocol
	modprobe mxs_raw_auart
	modprobe eq3_char_loop

	# button 
        modprobe gpio-keys
	modprobe evdev

	# CUL driver
	modprobe cdc-acm	 

	echo "OK"
}

stop () {
	/sbin/led power flash
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

