#!/bin/sh
#
# Start UnionFS
#

MMC=/dev/mmcblk0p1
MNTPOINT=/media

log(){
	echo "$1"
	logger -p user.info -t restore "$1"

}

do_overlay() {
	printf "mount user filesystem: "
	mount -t ubifs -o noatime ubi1:user /mnt/user || return 
	printf "OK\nmount unionFS: "
	modprobe unionfs || return
	mount -t unionfs -o dirs=/mnt/user=rw:/=ro unionfs /mnt/new_root || return
	cd /mnt/new_root || return
	printf "OK\nremount rootfs (noatime): "
	mount -o remount,noatime / || return     
	printf "OK\nmove dev,tmp,run: "
	mkdir -p /mnt/new_root/mnt/old_root || return
	mount -o move /dev /mnt/new_root/dev || return     
	mount -o move /tmp /mnt/new_root/tmp || return
	mount -o move /run /mnt/new_root/run || return
	printf "OK\nunmount sys,proc: "
	umount /sys || return
	umount /proc  || return
	printf "OK\npivot rootfs: "
	pivot_root . mnt/old_root || return
	printf "OK\nmount sys,proc: "
	mount /proc || return
	mount /sys || return
	return;
}

start() {
	
	if [ -f /.trigger_restore ]
	then
		/sbin/led info slow
		watchdog -t 5 /dev/watchdog
		log "restore triggered ..."
		if [ ! -b $MMC ] ; then
			log "no sd card found, waiting 10 s ..."
			sleep 10 
		fi
		if [  -b $MMC ] ; then 
			log "mount sd card"		
			mount $MMC $MNTPOINT
			if [ -f $MNTPOINT/fhem-backup-latest.txt ];then
				BCKFILE="`cat $MNTPOINT/fhem-backup-latest.txt`"
				if [ -f $MNTPOINT/$BCKFILE ] ;then
					log "found $BCKFILE"
					if zcat $MNTPOINT/$BCKFILE >/dev/null ;then
						log "backup file valid"
						log "Formating user file system"
						if ubidetach -p /dev/mtd7 && ubiformat  /dev/mtd7 && ubiattach -p /dev/mtd7 && ubimkvol /dev/ubi1 -N user -m
                				then
                        				log "Format OK"
                				else
                        				log "Format FAIL!"
                				fi
						log "mount user filesystem and restore $BCKFILE"	
						mount -t ubifs -o noatime ubi1:user /mnt/user && zcat $MNTPOINT/$BCKFILE | tar x -C /mnt/user 
						if [ $? -eq 0 ]; then
							/sbin/led info off
							log "restore OK"
						else
							echo "Error: restore fail!"
						fi
						umount /mnt/user

					else
						log "backup file invalid, restore canceled"
						/sbin/led power fast
						/sbin/led info fast
					fi
				fi
			else
				log "no backup file found"
			fi
			
			umount $MNTPOINT 
		fi
		rm /.trigger_restore
	 	killall watchdog
	fi

	if ubinfo /dev/ubi1 -N user 2>/dev/null >/dev/null
	then
		if do_overlay
		then
			echo "OK"
		else
			echo "FAIL"
		fi
	else
		echo "Fatal error! user filesystem not found!"
		/sbin/led power fast
		/sbin/led info fast
	fi
}

stop() {
	mount -o remount,ro /mnt/old_root
	mount -o remount,ro /mnt/old_root/mnt/user/
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

